version: '3.8'

services:
  todoapi:
    image: todoapi:latest
    ports:
      - "9080:9080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
